name: deploy release

on:
  workflow_call:
  workflow_dispatch:

concurrency:
  group: deploy-release
  cancel-in-progress: true

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Download latest backend binary
        uses: robinraju/release-downloader@v1
        with:
          latest: true
          fileName: backend
          out-file-path: .
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload binary and deploy script
        uses: appleboy/scp-action@v1.0.0
        with:
          host: ${{ secrets.SERVER_SSH_HOST }}
          username: ${{ secrets.SERVER_SSH_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          source: ./backend,./cicd/deploy.py
          target: /tmp/

      - name: Remote deploy
        uses: appleboy/ssh-action@v1.2.2
        with:
          host: ${{ secrets.SERVER_SSH_HOST }}
          username: ${{ secrets.SERVER_SSH_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            set -euo pipefail
            python3 /tmp/cicd/deploy.py \
              --binary-path /tmp/backend \
              --repo-url https://github.com/${{ github.repository }} \
              --api-key-chatgpt ${{ secrets.API_KEY_CHATGPT }} \
              --graphql-parent-path /langample/ \
              --panlex-sqlite-db-path ~/panlex.sqlite
