name: on push master

on:
  push:
    branches: [ main ]

permissions:
  contents: write

concurrency:
  group: on-push-master
  cancel-in-progress: true

jobs:
  build:
    uses: ./.github/workflows/build-release.yml
    secrets: inherit

  ansible:
    needs: build
    uses: ./.github/workflows/run-ansible.yml
    secrets: inherit

  deploy-rust:
    needs: ansible
    uses: ./.github/workflows/deploy-rust.yml
    secrets: inherit
